# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - make clean
    # you may remove this if you don't use vgo
    - go mod download
    #- touch {{ .Env.FILE_TO_TOUCH }}
builds:
  -
    env:
    - CGO_ENABLED=0
    main: ./cmd/path-shrinker/main.go
    binary: bin/path-shrinker
    goos:
      - darwin
      - linux
      - windows
archives:
  -
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
